/* BubblinCrude — commercial oil hubs (pricing, storage, loading, blend).
   Public geography and role — no assays required. */
(function (global) {
  "use strict";

  function Hub(o) {
    return Object.assign(
      {
        role: "loading",
        country: "",
        region: "",
        lat: 0,
        lon: 0,
        related_ids: [],
        notes: "",
      },
      o
    );
  }

  const hubs = [
    // ——— Americas ———
    Hub({
      id: "cushing",
      name: "Cushing",
      country: "United States",
      region: "North America",
      lat: 35.98,
      lon: -96.77,
      role: "pricing",
      related_ids: ["wti", "wts"],
      notes: "Pipeline crossroads and WTI futures delivery point; US storage capital.",
    }),
    Hub({
      id: "meh-houston",
      name: "Magellan East Houston",
      country: "United States",
      region: "North America",
      lat: 29.75,
      lon: -95.12,
      role: "pricing",
      related_ids: ["wti-houston", "midland", "lls"],
      notes: "USGC export pricing hub for Permian-quality light sweet (MEH / WTI Houston).",
    }),
    Hub({
      id: "loop",
      name: "LOOP",
      country: "United States",
      region: "North America",
      lat: 28.88,
      lon: -90.02,
      role: "loading",
      related_ids: ["mars", "poseidon", "southern-green-canyon"],
      notes: "Louisiana Offshore Oil Port — deepwater US import/export marine terminal.",
    }),
    Hub({
      id: "st-james",
      name: "St. James",
      country: "United States",
      region: "North America",
      lat: 30.0,
      lon: -90.85,
      role: "blend",
      related_ids: ["lls", "hls"],
      notes: "Louisiana pipeline hub for Light Louisiana Sweet and Gulf Coast grades.",
    }),
    Hub({
      id: "hardisty",
      name: "Hardisty",
      country: "Canada",
      region: "North America",
      lat: 52.67,
      lon: -111.31,
      role: "blend",
      related_ids: ["wcs", "cold-lake", "access-western-blend"],
      notes: "Alberta heavy-oil aggregation and WCS pricing/blend point.",
    }),
    Hub({
      id: "edmonton",
      name: "Edmonton / Fort Saskatchewan",
      country: "Canada",
      region: "North America",
      lat: 53.55,
      lon: -113.49,
      role: "blend",
      related_ids: ["condensate-blend", "syncrude", "cochin-condensate"],
      notes: "Western Canada light/synthetic and diluent pool gateway to Enbridge.",
    }),
    Hub({
      id: "westridge",
      name: "Westridge Marine Terminal",
      country: "Canada",
      region: "North America",
      lat: 49.29,
      lon: -122.95,
      role: "loading",
      related_ids: ["pacific-blend", "pacific-cold-lake"],
      notes: "Burnaby tanker dock for Trans Mountain dilbit exports to the Pacific.",
    }),
    Hub({
      id: "valdez",
      name: "Valdez",
      country: "United States",
      region: "North America",
      lat: 61.12,
      lon: -146.35,
      role: "loading",
      related_ids: ["ans"],
      notes: "Southern terminus of TAPS; Alaska North Slope marine loading.",
    }),
    Hub({
      id: "jose-ve",
      name: "Jose",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.1,
      lon: -64.85,
      role: "loading",
      related_ids: ["merey-16", "hamaca", "cerro-negro"],
      notes: "Orinoco upgrader and export complex east of Puerto La Cruz — Merey/SCO gateway.",
    }),
    Hub({
      id: "cayo-arima",
      name: "Cayo Arima / Jose waterfront",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.15,
      lon: -64.8,
      role: "storage",
      related_ids: ["merey-16"],
      notes: "Storage and marine berths serving the Jose industrial oil complex.",
    }),
    // ——— Europe / Med / Russia export ———
    Hub({
      id: "rotterdam",
      name: "Rotterdam / ARA",
      country: "Netherlands",
      region: "Europe",
      lat: 51.95,
      lon: 4.15,
      role: "pricing",
      related_ids: ["brent", "forties", "urals"],
      notes: "Northwest Europe refining and barge hub; ARA pricing complex.",
    }),
    Hub({
      id: "sullom-voe",
      name: "Sullom Voe",
      country: "United Kingdom",
      region: "Europe",
      lat: 60.45,
      lon: -1.3,
      role: "loading",
      related_ids: ["brent", "forties"],
      notes: "Shetland terminal for Brent-system North Sea crude.",
    }),
    Hub({
      id: "flotta-hub",
      name: "Flotta",
      country: "United Kingdom",
      region: "Europe",
      lat: 58.84,
      lon: -3.12,
      role: "loading",
      related_ids: ["flotta"],
      notes: "Orkney export terminal for Flotta Gold blend.",
    }),
    Hub({
      id: "ceyhan",
      name: "Ceyhan",
      country: "Turkey",
      region: "Europe",
      lat: 36.8,
      lon: 35.9,
      role: "loading",
      related_ids: ["btc", "azeri-light", "kirkuk"],
      notes: "Mediterranean end of BTC and historic Kirkuk line — Caspian/Iraqi loadings.",
    }),
    Hub({
      id: "primorsk",
      name: "Primorsk",
      country: "Russia",
      region: "Russia & CIS",
      lat: 60.34,
      lon: 28.62,
      role: "loading",
      related_ids: ["urals"],
      notes: "Baltic Sea Urals export terminal (Transneft).",
    }),
    Hub({
      id: "novorossiysk",
      name: "Novorossiysk",
      country: "Russia",
      region: "Russia & CIS",
      lat: 44.72,
      lon: 37.77,
      role: "loading",
      related_ids: ["urals", "cpc"],
      notes: "Black Sea crude port; Urals and CPC-system loadings.",
    }),
    Hub({
      id: "kozmino",
      name: "Kozmino",
      country: "Russia",
      region: "Russia & CIS",
      lat: 42.72,
      lon: 133.03,
      role: "loading",
      related_ids: ["espo"],
      notes: "Pacific end of ESPO pipeline — East Siberia grades to Asia.",
    }),
    Hub({
      id: "ust-luga",
      name: "Ust-Luga",
      country: "Russia",
      region: "Russia & CIS",
      lat: 59.67,
      lon: 28.32,
      role: "loading",
      related_ids: ["urals"],
      notes: "Baltic export complex supplementing Primorsk.",
    }),
    // ——— Middle East ———
    Hub({
      id: "ras-tanura",
      name: "Ras Tanura",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 26.64,
      lon: 50.16,
      role: "loading",
      related_ids: ["arab-light", "arab-medium", "arab-heavy", "arab-extra-light"],
      notes: "Primary Saudi Arabian Gulf crude export terminal.",
    }),
    Hub({
      id: "juaymah",
      name: "Juaymah",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 26.8,
      lon: 50.0,
      role: "loading",
      related_ids: ["arab-light", "arab-heavy"],
      notes: "Saudi Gulf loading terminal paired with Ras Tanura system.",
    }),
    Hub({
      id: "yanbu",
      name: "Yanbu",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 24.08,
      lon: 38.05,
      role: "loading",
      related_ids: ["arab-light", "arab-extra-light"],
      notes: "Red Sea terminal via Petroline — westbound Saudi crude.",
    }),
    Hub({
      id: "fujairah",
      name: "Fujairah",
      country: "United Arab Emirates",
      region: "Middle East",
      lat: 25.12,
      lon: 56.35,
      role: "storage",
      related_ids: ["murban", "upper-zakum", "dubai"],
      notes: "Indian Ocean storage and bunkering hub outside the Strait of Hormuz.",
    }),
    Hub({
      id: "das-island",
      name: "Das Island",
      country: "United Arab Emirates",
      region: "Middle East",
      lat: 25.15,
      lon: 52.87,
      role: "loading",
      related_ids: ["das"],
      notes: "ADNOC offshore loading island for Das blend.",
    }),
    Hub({
      id: "basrah-oil-terminal",
      name: "Basrah Oil Terminal",
      country: "Iraq",
      region: "Middle East",
      lat: 29.68,
      lon: 48.81,
      role: "loading",
      related_ids: ["basrah-light", "basrah-heavy", "basrah-medium"],
      notes: "Iraq’s main southern Gulf export terminal for Basrah grades.",
    }),
    Hub({
      id: "kharg",
      name: "Kharg Island",
      country: "Iran",
      region: "Middle East",
      lat: 29.24,
      lon: 50.31,
      role: "loading",
      related_ids: ["iranian-light", "iranian-heavy"],
      notes: "Historic Iranian Gulf crude export island.",
    }),
    Hub({
      id: "mina-al-ahmadi",
      name: "Mina Al Ahmadi",
      country: "Kuwait",
      region: "Middle East",
      lat: 29.07,
      lon: 48.15,
      role: "loading",
      related_ids: ["kuwait-export"],
      notes: "Kuwait’s primary crude export terminal.",
    }),
    // ——— Africa ———
    Hub({
      id: "bonny-terminal",
      name: "Bonny Terminal",
      country: "Nigeria",
      region: "Africa",
      lat: 4.45,
      lon: 7.17,
      role: "loading",
      related_ids: ["bonny-light", "qua-iboe"],
      notes: "Niger Delta export hub for Bonny Light and related sweets.",
    }),
    Hub({
      id: "forcados-terminal",
      name: "Forcados",
      country: "Nigeria",
      region: "Africa",
      lat: 5.35,
      lon: 5.4,
      role: "loading",
      related_ids: ["forcados"],
      notes: "Western Niger Delta marine terminal for Forcados blend.",
    }),
    Hub({
      id: "es-sider-hub",
      name: "Es Sider",
      country: "Libya",
      region: "Africa",
      lat: 30.64,
      lon: 18.35,
      role: "loading",
      related_ids: ["es-sider", "brega"],
      notes: "Libyan Mediterranean crude export terminal.",
    }),
    Hub({
      id: "skikda",
      name: "Skikda",
      country: "Algeria",
      region: "Africa",
      lat: 36.88,
      lon: 6.91,
      role: "loading",
      related_ids: ["saharan-blend"],
      notes: "Algerian Mediterranean port for Saharan Blend exports.",
    }),
    // ——— Asia Pacific ———
    Hub({
      id: "singapore",
      name: "Singapore",
      country: "Singapore",
      region: "Asia Pacific",
      lat: 1.29,
      lon: 103.85,
      role: "pricing",
      related_ids: ["dubai", "oman", "tapis"],
      notes: "Asia pricing, storage, and bunkering crossroads for Middle East and regional crudes.",
    }),
    Hub({
      id: "ulsan",
      name: "Ulsan",
      country: "South Korea",
      region: "Asia Pacific",
      lat: 35.5,
      lon: 129.4,
      role: "loading",
      related_ids: ["espo", "murban"],
      notes: "Major NE Asia refining port receiving Middle East and Far East crudes.",
    }),
    Hub({
      id: "ningbo-zhoushan",
      name: "Ningbo–Zhoushan",
      country: "China",
      region: "Asia Pacific",
      lat: 29.95,
      lon: 122.1,
      role: "loading",
      related_ids: ["espo", "arab-light", "castilla"],
      notes: "China’s largest crude import port complex.",
    }),
    Hub({
      id: "kimanis-hub",
      name: "Kimanis",
      country: "Malaysia",
      region: "Asia Pacific",
      lat: 5.62,
      lon: 115.88,
      role: "loading",
      related_ids: ["kimanis", "labuan"],
      notes: "Sabah crude export system on the South China Sea.",
    }),
  ];

  global.HUBS_DATA = { hubs: hubs };
})(typeof window !== "undefined" ? window : globalThis);
