/* BubblinCrude — commercial oil hubs (pricing, storage, loading, blend).
   Public geography and role — no assays required. */
(function (global) {
  "use strict";

  function Hub(o) {
    return Object.assign(
      {
        role: "loading",
        country: "",
        region: "",
        lat: 0,
        lon: 0,
        related_ids: [],
        notes: "",
      },
      o
    );
  }

  const hubs = [
    // ——— Americas ———
    Hub({
      id: "cushing",
      name: "Cushing",
      country: "United States",
      region: "North America",
      lat: 35.98,
      lon: -96.77,
      role: "pricing",
      related_ids: ["wti", "wts", "scoop-stack"],
      notes: "Pipeline crossroads and WTI futures delivery point; US storage capital.",
    }),
    Hub({
      id: "meh-houston",
      name: "Magellan East Houston",
      country: "United States",
      region: "North America",
      lat: 29.75,
      lon: -95.12,
      role: "pricing",
      related_ids: ["eagle-ford", "midland", "wti-houston", "wtl", "delaware", "spr-big-hill-sweet", "spr-big-hill-sour", "spr-bryan-mound-sweet", "spr-bryan-mound-sour"],
      notes: "USGC export pricing hub for Permian-quality light sweet (MEH / WTI Houston).",
    }),
    Hub({
      id: "loop",
      name: "LOOP",
      country: "United States",
      region: "North America",
      lat: 28.88,
      lon: -90.02,
      role: "loading",
      related_ids: ["mars", "thunder-horse", "southern-green-canyon", "poseidon", "cascade-chinook", "southern-peninsula", "bonito", "shenzi", "hoover-diana", "hoops-blend"],
      notes: "Louisiana Offshore Oil Port — deepwater US import/export marine terminal.",
    }),
    Hub({
      id: "st-james",
      name: "St. James",
      country: "United States",
      region: "North America",
      lat: 30.0,
      lon: -90.85,
      role: "blend",
      related_ids: ["lls", "hls", "spr-bayou-choctaw-sweet", "spr-bayou-choctaw-sour", "spr-west-hackberry-sweet", "spr-west-hackberry-sour"],
      notes: "Louisiana pipeline hub for Light Louisiana Sweet and Gulf Coast grades.",
    }),
    Hub({
      id: "hardisty",
      name: "Hardisty",
      country: "Canada",
      region: "North America",
      lat: 52.67,
      lon: -111.31,
      role: "blend",
      related_ids: ["wcs", "cold-lake", "access-western-blend", "christina-lake", "bow-river", "lloydminster", "kearl", "surmont", "peace-river", "conventional-heavy", "premium-conventional-heavy", "synbit-blend", "bow-river-south", "clearwater-heavy", "seal-heavy", "wabasca-heavy", "western-canadian-blend", "borealis-heavy-blend", "canadian-natural-high-tan", "fort-hills-dilbit", "leismer-corner-blend", "long-lake-heavy-dilbit", "western-canada-dilbit", "long-lake-heavy", "petrochina-blend", "statoil-cheecham-synbit", "surmont-heavy-blend", "surmont-mix-a"],
      notes: "Alberta heavy-oil aggregation and WCS pricing/blend point.",
    }),
    Hub({
      id: "edmonton",
      name: "Edmonton / Fort Saskatchewan",
      country: "Canada",
      region: "North America",
      lat: 53.55,
      lon: -113.49,
      role: "blend",
      related_ids: ["syncrude", "albian", "msw", "lsb", "cochin-condensate", "condensate-blend", "fort-saskatchewan-condensate", "peace-condensate", "pembina-condensate", "rangeland-condensate", "southern-lights-diluent", "federated", "light-smiley", "peace-msw-feeder", "pembina-blend", "secure-sask-light", "rainbow", "hardisty-light", "medium-gibson-sour", "midale", "peace-pipe-sour", "conventional-heavy", "hardisty-synthetic", "medium-sour-blend", "msw-superior", "premium-conventional-heavy", "premium-synthetic", "synthetic-sweet-blend", "bc-light", "boundary-lake", "koch-alberta", "moose-jaw-tops", "pembina-light-sour", "cnrl-light-sweet-synthetic", "husky-synthetic-blend", "long-lake-light-synthetic", "premium-albian-synthetic", "shell-synthetic-light", "suncor-synthetic-a", "clearwater-heavy", "fosterton", "lloyd-kerrobert", "seal-heavy", "smiley-coleville", "wabasca-heavy", "western-canadian-blend", "suncor-synthetic-h"],
      notes: "Western Canada light/synthetic and diluent pool gateway to Enbridge.",
    }),
    Hub({
      id: "westridge",
      name: "Westridge Marine Terminal",
      country: "Canada",
      region: "North America",
      lat: 49.29,
      lon: -122.95,
      role: "loading",
      related_ids: ["pacific-blend", "pacific-cold-lake"],
      notes: "Burnaby tanker dock for Trans Mountain dilbit exports to the Pacific.",
    }),
    Hub({
      id: "valdez",
      name: "Valdez",
      country: "United States",
      region: "North America",
      lat: 61.12,
      lon: -146.35,
      role: "loading",
      related_ids: ["ans"],
      notes: "Southern terminus of TAPS; Alaska North Slope marine loading.",
    }),
    Hub({
      id: "jose-ve",
      name: "Jose",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.1,
      lon: -64.85,
      role: "loading",
      related_ids: ["merey-16", "cerro-negro", "hamaca", "zuata", "petrocedeno"],
      notes: "Orinoco upgrader and export complex east of Puerto La Cruz — Merey/SCO gateway.",
    }),
    Hub({
      id: "cayo-arima",
      name: "Cayo Arima / Jose waterfront",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.15,
      lon: -64.8,
      role: "storage",
      related_ids: ["merey-16"],
      notes: "Storage and marine berths serving the Jose industrial oil complex.",
    }),
    // ——— Europe / Med / Russia export ———
    Hub({
      id: "rotterdam",
      name: "Rotterdam / ARA",
      country: "Netherlands",
      region: "Europe",
      lat: 51.95,
      lon: 4.15,
      role: "pricing",
      related_ids: ["brent", "forties"],
      notes: "Northwest Europe refining and barge hub; ARA pricing complex.",
    }),
    Hub({
      id: "sullom-voe",
      name: "Sullom Voe",
      country: "United Kingdom",
      region: "Europe",
      lat: 60.45,
      lon: -1.3,
      role: "loading",
      related_ids: ["brent", "forties", "ninian", "alwyn"],
      notes: "Shetland terminal for Brent-system North Sea crude.",
    }),
    Hub({
      id: "flotta-hub",
      name: "Flotta",
      country: "United Kingdom",
      region: "Europe",
      lat: 58.84,
      lon: -3.12,
      role: "loading",
      related_ids: ["flotta"],
      notes: "Orkney export terminal for Flotta Gold blend.",
    }),
    Hub({
      id: "ceyhan",
      name: "Ceyhan",
      country: "Turkey",
      region: "Europe",
      lat: 36.8,
      lon: 35.9,
      role: "loading",
      related_ids: ["azeri-light", "kirkuk", "btc"],
      notes: "Mediterranean end of BTC and historic Kirkuk line — Caspian/Iraqi loadings.",
    }),
    Hub({
      id: "primorsk",
      name: "Primorsk",
      country: "Russia",
      region: "Russia & CIS",
      lat: 60.34,
      lon: 28.62,
      role: "loading",
      related_ids: ["urals", "siberian-light"],
      notes: "Baltic Sea Urals export terminal (Transneft).",
    }),
    Hub({
      id: "novorossiysk",
      name: "Novorossiysk",
      country: "Russia",
      region: "Russia & CIS",
      lat: 44.72,
      lon: 37.77,
      role: "loading",
      related_ids: ["cpc", "urals", "tengiz", "kashagan", "kebco"],
      notes: "Black Sea crude port; Urals and CPC-system loadings.",
    }),
    Hub({
      id: "kozmino",
      name: "Kozmino",
      country: "Russia",
      region: "Russia & CIS",
      lat: 42.72,
      lon: 133.03,
      role: "loading",
      related_ids: ["espo"],
      notes: "Pacific end of ESPO pipeline — East Siberia grades to Asia.",
    }),
    Hub({
      id: "ust-luga",
      name: "Ust-Luga",
      country: "Russia",
      region: "Russia & CIS",
      lat: 59.67,
      lon: 28.32,
      role: "loading",
      related_ids: ["urals", "siberian-light"],
      notes: "Baltic export complex supplementing Primorsk.",
    }),
    // ——— Middle East ———
    Hub({
      id: "ras-tanura",
      name: "Ras Tanura",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 26.64,
      lon: 50.16,
      role: "loading",
      related_ids: ["arab-light", "arab-heavy", "arab-medium", "arab-extra-light", "arab-super-light"],
      notes: "Primary Saudi Arabian Gulf crude export terminal.",
    }),
    Hub({
      id: "juaymah",
      name: "Juaymah",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 26.8,
      lon: 50.0,
      role: "loading",
      related_ids: ["arab-light", "arab-heavy"],
      notes: "Saudi Gulf loading terminal paired with Ras Tanura system.",
    }),
    Hub({
      id: "yanbu",
      name: "Yanbu",
      country: "Saudi Arabia",
      region: "Middle East",
      lat: 24.08,
      lon: 38.05,
      role: "loading",
      related_ids: ["arab-light", "arab-extra-light", "arab-super-light"],
      notes: "Red Sea terminal via Petroline — westbound Saudi crude.",
    }),
    Hub({
      id: "fujairah",
      name: "Fujairah",
      country: "United Arab Emirates",
      region: "Middle East",
      lat: 25.12,
      lon: 56.35,
      role: "storage",
      related_ids: ["murban", "upper-zakum", "al-shaheen", "dubai", "lower-zakum"],
      notes: "Indian Ocean storage and bunkering hub outside the Strait of Hormuz.",
    }),
    Hub({
      id: "das-island",
      name: "Das Island",
      country: "United Arab Emirates",
      region: "Middle East",
      lat: 25.15,
      lon: 52.87,
      role: "loading",
      related_ids: ["das"],
      notes: "ADNOC offshore loading island for Das blend.",
    }),
    Hub({
      id: "basrah-oil-terminal",
      name: "Basrah Oil Terminal",
      country: "Iraq",
      region: "Middle East",
      lat: 29.68,
      lon: 48.81,
      role: "loading",
      related_ids: ["basrah-light", "basrah-heavy", "basrah-medium"],
      notes: "Iraq’s main southern Gulf export terminal for Basrah grades.",
    }),
    Hub({
      id: "kharg",
      name: "Kharg Island",
      country: "Iran",
      region: "Middle East",
      lat: 29.24,
      lon: 50.31,
      role: "loading",
      related_ids: ["iranian-light", "iranian-heavy", "forozan", "iranian-medium", "sirri", "soroosh", "nowruz"],
      notes: "Historic Iranian Gulf crude export island.",
    }),
    Hub({
      id: "mina-al-ahmadi",
      name: "Mina Al Ahmadi",
      country: "Kuwait",
      region: "Middle East",
      lat: 29.07,
      lon: 48.15,
      role: "loading",
      related_ids: ["kuwait-export", "khafji"],
      notes: "Kuwait’s primary crude export terminal.",
    }),
    // ——— Africa ———
    Hub({
      id: "bonny-terminal",
      name: "Bonny Terminal",
      country: "Nigeria",
      region: "Africa",
      lat: 4.45,
      lon: 7.17,
      role: "loading",
      related_ids: ["bonny-light", "yoho"],
      notes: "Niger Delta export hub for Bonny Light and related sweets.",
    }),
    Hub({
      id: "forcados-terminal",
      name: "Forcados",
      country: "Nigeria",
      region: "Africa",
      lat: 5.35,
      lon: 5.4,
      role: "loading",
      related_ids: ["forcados"],
      notes: "Western Niger Delta marine terminal for Forcados blend.",
    }),
    Hub({
      id: "es-sider-hub",
      name: "Es Sider",
      country: "Libya",
      region: "Africa",
      lat: 30.64,
      lon: 18.35,
      role: "loading",
      related_ids: ["es-sider", "amna", "brega", "sirtica"],
      notes: "Libyan Mediterranean crude export terminal.",
    }),
    Hub({
      id: "skikda",
      name: "Skikda",
      country: "Algeria",
      region: "Africa",
      lat: 36.88,
      lon: 6.91,
      role: "loading",
      related_ids: ["saharan-blend", "zarzaitine"],
      notes: "Algerian Mediterranean port for Saharan Blend exports.",
    }),
    // ——— Asia Pacific ———
    Hub({
      id: "singapore",
      name: "Singapore",
      country: "Singapore",
      region: "Asia Pacific",
      lat: 1.29,
      lon: 103.85,
      role: "pricing",
      related_ids: ["tapis", "oman", "dubai"],
      notes: "Asia pricing, storage, and bunkering crossroads for Middle East and regional crudes.",
    }),
    Hub({
      id: "ulsan",
      name: "Ulsan",
      country: "South Korea",
      region: "Asia Pacific",
      lat: 35.5,
      lon: 129.4,
      role: "loading",
      related_ids: [],
      notes: "Major NE Asia refining port receiving Middle East and Far East crudes.",
    }),
    Hub({
      id: "ningbo-zhoushan",
      name: "Ningbo–Zhoushan",
      country: "China",
      region: "Asia Pacific",
      lat: 29.95,
      lon: 122.1,
      role: "loading",
      related_ids: [],
      notes: "China’s largest crude import port complex.",
    }),
    Hub({
      id: "kimanis-hub",
      name: "Kimanis",
      country: "Malaysia",
      region: "Asia Pacific",
      lat: 5.62,
      lon: 115.88,
      role: "loading",
      related_ids: ["kimanis"],
      notes: "Sabah crude export system on the South China Sea.",
    }),
    // ——— Added loading terminals ———
    Hub({
      id: "clearbrook",
      name: "Clearbrook",
      country: "United States",
      region: "North America",
      lat: 47.85,
      lon: -96.38,
      role: "blend",
      related_ids: ["bakken"],
      notes: "Enbridge Mainline Bakken receipt; Midwest pipeline hub.",
    }),
    Hub({
      id: "guernsey",
      name: "Guernsey",
      country: "United States",
      region: "North America",
      lat: 42.27,
      lon: -104.74,
      role: "blend",
      related_ids: ["niobrara", "powder-river"],
      notes: "Wyoming pipeline junction for DJ and Powder River barrels.",
    }),
    Hub({
      id: "long-beach",
      name: "Long Beach / LA",
      country: "United States",
      region: "North America",
      lat: 33.75,
      lon: -118.22,
      role: "loading",
      related_ids: ["kern-river", "midway-sunset"],
      notes: "San Pedro Bay docks for California heavy crude.",
    }),
    Hub({
      id: "salt-lake",
      name: "Salt Lake",
      country: "United States",
      region: "North America",
      lat: 40.76,
      lon: -111.9,
      role: "blend",
      related_ids: ["uinta-waxy"],
      notes: "Wasatch Front refining destination for Uinta waxy crude.",
    }),
    Hub({
      id: "philadelphia",
      name: "Philadelphia",
      country: "United States",
      region: "North America",
      lat: 39.86,
      lon: -75.2,
      role: "loading",
      related_ids: ["pennsylvania-grade"],
      notes: "Delaware River refining port for Pennsylvania Grade and imports.",
    }),
    Hub({
      id: "whiffen-head",
      name: "Whiffen Head",
      country: "Canada",
      region: "North America",
      lat: 47.76,
      lon: -54.02,
      role: "loading",
      related_ids: ["hibernia", "terra-nova", "hebron", "white-rose"],
      notes: "Newfoundland transshipment terminal for Jeanne d'Arc grades.",
    }),
    Hub({
      id: "cayo-arcas",
      name: "Cayo Arcas",
      country: "Mexico",
      region: "Latin America",
      lat: 20.21,
      lon: -91.98,
      role: "loading",
      related_ids: ["maya"],
      notes: "Campeche Sound SPM; Maya export loading.",
    }),
    Hub({
      id: "dos-bocas",
      name: "Dos Bocas",
      country: "Mexico",
      region: "Latin America",
      lat: 18.43,
      lon: -93.19,
      role: "loading",
      related_ids: ["olmeca", "isthmus"],
      notes: "Tabasco marine terminal for Isthmus and Olmeca.",
    }),
    Hub({
      id: "altamira-port",
      name: "Altamira",
      country: "Mexico",
      region: "Latin America",
      lat: 22.49,
      lon: -97.86,
      role: "loading",
      related_ids: ["altamira"],
      notes: "Tamaulipas port for Altamira heavy.",
    }),
    Hub({
      id: "covenas",
      name: "Coveñas",
      country: "Colombia",
      region: "Latin America",
      lat: 9.4,
      lon: -75.69,
      role: "loading",
      related_ids: ["castilla", "vasconia", "cusiana", "cano-limon"],
      notes: "Caribbean export terminal for Colombian pipeline crudes.",
    }),
    Hub({
      id: "balao",
      name: "Balao",
      country: "Ecuador",
      region: "Latin America",
      lat: 1.05,
      lon: -79.72,
      role: "loading",
      related_ids: ["oriente", "napo"],
      notes: "Esmeraldas-area loading for Oriente and Napo.",
    }),
    Hub({
      id: "angra-tebig",
      name: "Angra dos Reis (TEBIG)",
      country: "Brazil",
      region: "Latin America",
      lat: -23.01,
      lon: -44.32,
      role: "loading",
      related_ids: ["marlim", "roncador", "peregrino", "albacora", "frade", "papa-terra", "bacalhau"],
      notes: "Petrobras Campos Basin transshipment terminal.",
    }),
    Hub({
      id: "porto-acu",
      name: "Porto do Açu",
      country: "Brazil",
      region: "Latin America",
      lat: -21.82,
      lon: -41.02,
      role: "loading",
      related_ids: ["lula", "buzios", "tupi", "sapinhoa", "atapu", "lapa", "mero", "sururu", "sepia"],
      notes: "São João da Barra port for Santos Basin pre-salt.",
    }),
    Hub({
      id: "bajo-grande",
      name: "Bajo Grande",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.52,
      lon: -71.64,
      role: "loading",
      related_ids: ["boscan", "bachaquero", "laguna", "tia-juana-light", "tia-juana-heavy"],
      notes: "Lake Maracaibo loading terminal.",
    }),
    Hub({
      id: "puerto-la-cruz",
      name: "Puerto La Cruz",
      country: "Venezuela",
      region: "Latin America",
      lat: 10.23,
      lon: -64.64,
      role: "loading",
      related_ids: ["mesa-30", "santa-barbara", "el-furrial"],
      notes: "Eastern Venezuela refining and export port.",
    }),
    Hub({
      id: "caleta-olivia",
      name: "Caleta Olivia",
      country: "Argentina",
      region: "Latin America",
      lat: -46.44,
      lon: -67.53,
      role: "loading",
      related_ids: ["escalante"],
      notes: "San Jorge Gulf loading for Escalante.",
    }),
    Hub({
      id: "puerto-rosales",
      name: "Puerto Rosales",
      country: "Argentina",
      region: "Latin America",
      lat: -38.9,
      lon: -62.08,
      role: "loading",
      related_ids: ["medanito"],
      notes: "Bahía Blanca pipeline terminal for Neuquén grades.",
    }),
    Hub({
      id: "bayovar",
      name: "Bayóvar",
      country: "Peru",
      region: "Latin America",
      lat: -5.8,
      lon: -81.05,
      role: "loading",
      related_ids: ["mayna"],
      notes: "Piura marine terminal for northern Peruvian crude.",
    }),
    Hub({
      id: "galeota-point",
      name: "Galeota Point",
      country: "Trinidad and Tobago",
      region: "Latin America",
      lat: 10.14,
      lon: -60.99,
      role: "loading",
      related_ids: ["galeota"],
      notes: "Southeast Trinidad marine loading.",
    }),
    Hub({
      id: "stabroek-fpso",
      name: "Stabroek FPSO",
      country: "Guyana",
      region: "Latin America",
      lat: 8.0,
      lon: -56.8,
      role: "loading",
      related_ids: ["liza", "unity", "golden-arrowhead", "payara-gold"],
      notes: "Offshore offtake for Liza, Payara, and related Stabroek grades.",
    }),
    Hub({
      id: "qua-iboe-terminal",
      name: "Qua Iboe",
      country: "Nigeria",
      region: "Africa",
      lat: 4.33,
      lon: 8.0,
      role: "loading",
      related_ids: ["qua-iboe"],
      notes: "ExxonMobil Qua Iboe marine terminal.",
    }),
    Hub({
      id: "brass-terminal",
      name: "Brass",
      country: "Nigeria",
      region: "Africa",
      lat: 4.31,
      lon: 6.24,
      role: "loading",
      related_ids: ["brass-river"],
      notes: "Brass River export terminal.",
    }),
    Hub({
      id: "escravos-terminal",
      name: "Escravos",
      country: "Nigeria",
      region: "Africa",
      lat: 5.61,
      lon: 5.08,
      role: "loading",
      related_ids: ["escravos"],
      notes: "Chevron Escravos export terminal.",
    }),
    Hub({
      id: "malongo",
      name: "Malongo",
      country: "Angola",
      region: "Africa",
      lat: -5.55,
      lon: 12.19,
      role: "loading",
      related_ids: ["cabinda", "nemba"],
      notes: "Cabinda Gulf loading for Cabinda and Nemba.",
    }),
    Hub({
      id: "palanca-terminal",
      name: "Palanca",
      country: "Angola",
      region: "Africa",
      lat: -6.07,
      lon: 12.35,
      role: "loading",
      related_ids: ["palanca"],
      notes: "Block 3 Palanca marine terminal.",
    }),
    Hub({
      id: "girassol-load",
      name: "Girassol",
      country: "Angola",
      region: "Africa",
      lat: -7.65,
      lon: 11.7,
      role: "loading",
      related_ids: ["dalia", "girassol", "pazflor", "clov"],
      notes: "Block 17 FPSO loading (Girassol, Dalia, Pazflor, CLOV).",
    }),
    Hub({
      id: "kizomba-load",
      name: "Kizomba",
      country: "Angola",
      region: "Africa",
      lat: -6.3,
      lon: 11.3,
      role: "loading",
      related_ids: ["saxi-batuque", "hungo", "kissanje", "mondo"],
      notes: "Block 15 FPSO loading (Hungo, Kissanje, Saxi, Mondo).",
    }),
    Hub({
      id: "kaombo-load",
      name: "Kaombo",
      country: "Angola",
      region: "Africa",
      lat: -7.7,
      lon: 11.5,
      role: "loading",
      related_ids: ["gindungo", "mostarda", "saturno"],
      notes: "Block 32 FPSO loading (Gindungo, Mostarda, Saturno).",
    }),
    Hub({
      id: "plutonio-load",
      name: "Greater Plutonio",
      country: "Angola",
      region: "Africa",
      lat: -7.8,
      lon: 12.1,
      role: "loading",
      related_ids: ["plutonio"],
      notes: "Block 18 FPSO loading.",
    }),
    Hub({
      id: "djeno-terminal",
      name: "Djeno",
      country: "Congo",
      region: "Africa",
      lat: -4.77,
      lon: 11.88,
      role: "loading",
      related_ids: ["djeno"],
      notes: "Congolese Atlantic export terminal.",
    }),
    Hub({
      id: "cap-lopez",
      name: "Cap Lopez",
      country: "Gabon",
      region: "Africa",
      lat: -0.63,
      lon: 8.73,
      role: "loading",
      related_ids: ["mandji"],
      notes: "Port-Gentil loading for Mandji.",
    }),
    Hub({
      id: "gamba-terminal",
      name: "Gamba",
      country: "Gabon",
      region: "Africa",
      lat: -2.78,
      lon: 10.0,
      role: "loading",
      related_ids: ["rabi"],
      notes: "Southern Gabon terminal for Rabi.",
    }),
    Hub({
      id: "kribi-terminal",
      name: "Kribi",
      country: "Cameroon",
      region: "Africa",
      lat: 2.94,
      lon: 9.91,
      role: "loading",
      related_ids: ["doba"],
      notes: "Chad–Cameroon pipeline marine terminal (Doba).",
    }),
    Hub({
      id: "kole-terminal",
      name: "Kole",
      country: "Cameroon",
      region: "Africa",
      lat: 4.22,
      lon: 8.55,
      role: "loading",
      related_ids: ["kole"],
      notes: "Rio del Rey marine terminal.",
    }),
    Hub({
      id: "ras-shukheir",
      name: "Ras Shukheir",
      country: "Egypt",
      region: "Africa",
      lat: 28.14,
      lon: 33.28,
      role: "loading",
      related_ids: ["suez-blend", "belayim", "zeit-bay"],
      notes: "Gulf of Suez loading for Egyptian blend grades.",
    }),
    Hub({
      id: "bashayer",
      name: "Bashayer",
      country: "Sudan",
      region: "Africa",
      lat: 19.6,
      lon: 37.22,
      role: "loading",
      related_ids: ["dar-blend", "nile-blend"],
      notes: "Port Sudan marine terminal for Nile and Dar blends.",
    }),
    Hub({
      id: "zawiya-terminal",
      name: "Zawiya",
      country: "Libya",
      region: "Africa",
      lat: 32.78,
      lon: 12.73,
      role: "loading",
      related_ids: ["el-sharara"],
      notes: "Western Libya terminal; Sharara pipeline outlet.",
    }),
    Hub({
      id: "mellitah-hub",
      name: "Mellitah",
      country: "Libya",
      region: "Africa",
      lat: 32.53,
      lon: 12.05,
      role: "loading",
      related_ids: ["al-jurf", "mellitah"],
      notes: "Mellitah complex for western Libyan and NC-41 barrels.",
    }),
    Hub({
      id: "bejaia-hub",
      name: "Béjaïa",
      country: "Algeria",
      region: "Africa",
      lat: 36.75,
      lon: 5.08,
      role: "loading",
      related_ids: ["algerian-condensate"],
      notes: "Mediterranean condensate loading port.",
    }),
    Hub({
      id: "mongstad",
      name: "Mongstad",
      country: "Norway",
      region: "Europe",
      lat: 60.81,
      lon: 5.03,
      role: "loading",
      related_ids: ["johan-sverdrup", "troll"],
      notes: "Norwegian west-coast terminal; Troll and Johan Sverdrup.",
    }),
    Hub({
      id: "sture",
      name: "Sture",
      country: "Norway",
      region: "Europe",
      lat: 60.62,
      lon: 4.85,
      role: "loading",
      related_ids: ["oseberg", "grane", "martin-linge"],
      notes: "Oseberg and Grane export terminal.",
    }),
    Hub({
      id: "teesside",
      name: "Teesside",
      country: "United Kingdom",
      region: "Europe",
      lat: 54.64,
      lon: -1.15,
      role: "loading",
      related_ids: ["ekofisk", "culzean"],
      notes: "Norpipe landfall; Ekofisk and some UK condensate.",
    }),
    Hub({
      id: "melkoya",
      name: "Melkøya",
      country: "Norway",
      region: "Europe",
      lat: 70.67,
      lon: 23.6,
      role: "loading",
      related_ids: ["snohvit"],
      notes: "Hammerfest LNG / Snøhvit condensate.",
    }),
    Hub({
      id: "nyhamna",
      name: "Nyhamna",
      country: "Norway",
      region: "Europe",
      lat: 62.84,
      lon: 7.16,
      role: "loading",
      related_ids: ["aasta-hansteen", "ormen-lange"],
      notes: "Ormen Lange and Polarled condensate plant.",
    }),
    Hub({
      id: "karsto",
      name: "Kårstø",
      country: "Norway",
      region: "Europe",
      lat: 59.28,
      lon: 5.51,
      role: "loading",
      related_ids: ["gudrun"],
      notes: "Gas-plant condensate and NGL export.",
    }),
    Hub({
      id: "fredericia",
      name: "Fredericia",
      country: "Denmark",
      region: "Europe",
      lat: 55.56,
      lon: 9.75,
      role: "loading",
      related_ids: ["duc"],
      notes: "Danish Underground Consortium export terminal.",
    }),
    Hub({
      id: "hound-point",
      name: "Hound Point",
      country: "United Kingdom",
      region: "Europe",
      lat: 56.02,
      lon: -3.0,
      role: "loading",
      related_ids: ["dumbarton", "harding"],
      notes: "Firth of Forth Forties-system tanker loading.",
    }),
    Hub({
      id: "de-kastri",
      name: "De-Kastri",
      country: "Russia",
      region: "Russia & CIS",
      lat: 51.47,
      lon: 140.77,
      role: "loading",
      related_ids: ["sokol"],
      notes: "Sakhalin-1 Sokol loading port.",
    }),
    Hub({
      id: "prigorodnoye",
      name: "Prigorodnoye",
      country: "Russia",
      region: "Russia & CIS",
      lat: 46.63,
      lon: 142.91,
      role: "loading",
      related_ids: ["vityaz"],
      notes: "Sakhalin-2 Prigorodnoye export terminal.",
    }),
    Hub({
      id: "arctic-gate",
      name: "Arctic Gate",
      country: "Russia",
      region: "Russia & CIS",
      lat: 71.0,
      lon: 73.7,
      role: "loading",
      related_ids: ["novy-port"],
      notes: "Novy Port / Mys Kamenny Arctic loading tower.",
    }),
    Hub({
      id: "halul",
      name: "Halul Island",
      country: "Qatar",
      region: "Middle East",
      lat: 25.67,
      lon: 52.41,
      role: "loading",
      related_ids: ["qatar-marine"],
      notes: "Qatar Marine crude loading island.",
    }),
    Hub({
      id: "mesaieed",
      name: "Mesaieed",
      country: "Qatar",
      region: "Middle East",
      lat: 24.99,
      lon: 51.55,
      role: "loading",
      related_ids: ["qatar-land"],
      notes: "Qatar Land / Dukhan export terminal.",
    }),
    Hub({
      id: "ras-laffan",
      name: "Ras Laffan",
      country: "Qatar",
      region: "Middle East",
      lat: 25.91,
      lon: 51.58,
      role: "loading",
      related_ids: ["qatar-condensate"],
      notes: "North Field condensate and LNG liquids.",
    }),
    Hub({
      id: "sitra",
      name: "Sitra",
      country: "Bahrain",
      region: "Middle East",
      lat: 26.15,
      lon: 50.62,
      role: "loading",
      related_ids: ["banoco"],
      notes: "Bahrain Banoco export terminal.",
    }),
    Hub({
      id: "ash-shihr",
      name: "Ash Shihr",
      country: "Yemen",
      region: "Middle East",
      lat: 14.75,
      lon: 49.61,
      role: "loading",
      related_ids: ["masila"],
      notes: "Masila export terminal.",
    }),
    Hub({
      id: "ras-isa",
      name: "Ras Isa",
      country: "Yemen",
      region: "Middle East",
      lat: 15.21,
      lon: 42.67,
      role: "loading",
      related_ids: ["marib"],
      notes: "Marib pipeline Red Sea terminal.",
    }),
    Hub({
      id: "assaluyeh",
      name: "Assaluyeh",
      country: "Iran",
      region: "Middle East",
      lat: 27.46,
      lon: 52.61,
      role: "loading",
      related_ids: ["south-pars"],
      notes: "South Pars condensate loading.",
    }),
    Hub({
      id: "mina-al-fahal",
      name: "Mina Al Fahal",
      country: "Oman",
      region: "Middle East",
      lat: 23.63,
      lon: 58.51,
      role: "loading",
      related_ids: ["oman"],
      notes: "Muscat-area loading for Oman export crude.",
    }),
    Hub({
      id: "ruwais",
      name: "Ruwais",
      country: "United Arab Emirates",
      region: "Middle East",
      lat: 24.15,
      lon: 52.73,
      role: "loading",
      related_ids: ["murban-condensate"],
      notes: "ADNOC Ruwais condensate and refined-product complex.",
    }),
    Hub({
      id: "kertih",
      name: "Kertih",
      country: "Malaysia",
      region: "Asia Pacific",
      lat: 4.51,
      lon: 103.45,
      role: "loading",
      related_ids: ["tapis", "terengganu"],
      notes: "Terengganu marine terminal; Tapis system.",
    }),
    Hub({
      id: "labuan-terminal",
      name: "Labuan",
      country: "Malaysia",
      region: "Asia Pacific",
      lat: 5.27,
      lon: 115.25,
      role: "loading",
      related_ids: ["labuan"],
      notes: "Labuan Island crude export terminal.",
    }),
    Hub({
      id: "dumai",
      name: "Dumai",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 1.69,
      lon: 101.45,
      role: "loading",
      related_ids: ["minas", "duri"],
      notes: "Sumatra loading for Minas and Duri.",
    }),
    Hub({
      id: "senipah-hub",
      name: "Senipah",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: -1.0,
      lon: 117.25,
      role: "loading",
      related_ids: ["senipah"],
      notes: "Mahakam condensate and crude blend point.",
    }),
    Hub({
      id: "bontang-hub",
      name: "Bontang",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 0.13,
      lon: 117.48,
      role: "loading",
      related_ids: ["bontang-condensate"],
      notes: "East Kalimantan LNG plant condensate return.",
    }),
    Hub({
      id: "long-island-point",
      name: "Long Island Point",
      country: "Australia",
      region: "Asia Pacific",
      lat: -38.31,
      lon: 145.22,
      role: "loading",
      related_ids: ["gippsland", "gippsland-condensate"],
      notes: "Western Port loading for Gippsland crude and condensate.",
    }),
    Hub({
      id: "withnell-bay",
      name: "Withnell Bay",
      country: "Australia",
      region: "Asia Pacific",
      lat: -20.6,
      lon: 116.77,
      role: "loading",
      related_ids: ["northwest-shelf"],
      notes: "Karratha NWS condensate loading.",
    }),
    Hub({
      id: "darwin-lng",
      name: "Darwin LNG",
      country: "Australia",
      region: "Asia Pacific",
      lat: -12.52,
      lon: 130.89,
      role: "loading",
      related_ids: ["ichthys"],
      notes: "Bladin Point; Ichthys condensate.",
    }),
    Hub({
      id: "barrow-gorgon",
      name: "Barrow Island / Gorgon",
      country: "Australia",
      region: "Asia Pacific",
      lat: -20.82,
      lon: 115.39,
      role: "loading",
      related_ids: ["gorgon-condensate"],
      notes: "Gorgon condensate offtake.",
    }),
    Hub({
      id: "kumul",
      name: "Kumul",
      country: "Papua New Guinea",
      region: "Asia Pacific",
      lat: -8.12,
      lon: 144.52,
      role: "loading",
      related_ids: ["kutubu"],
      notes: "Gulf of Papua marine terminal for Kutubu.",
    }),
    Hub({
      id: "vung-tau",
      name: "Vung Tau",
      country: "Vietnam",
      region: "Asia Pacific",
      lat: 10.39,
      lon: 107.14,
      role: "loading",
      related_ids: ["bach-ho", "rang-dong"],
      notes: "Cuu Long Basin loading for Bach Ho and Rang Dong.",
    }),
    Hub({
      id: "lumut-brunei",
      name: "Lumut / Seria",
      country: "Brunei",
      region: "Asia Pacific",
      lat: 4.67,
      lon: 114.46,
      role: "loading",
      related_ids: ["champion", "seria-light"],
      notes: "Brunei export for Seria Light and Champion.",
    }),
    Hub({
      id: "jawahar-dweep",
      name: "Jawahar Dweep",
      country: "India",
      region: "Asia Pacific",
      lat: 18.95,
      lon: 72.85,
      role: "loading",
      related_ids: ["mumbai-high"],
      notes: "Mumbai harbour loading for Mumbai High.",
    }),
    Hub({
      id: "bhogat",
      name: "Bhogat",
      country: "India",
      region: "Asia Pacific",
      lat: 22.16,
      lon: 69.27,
      role: "loading",
      related_ids: ["mangala"],
      notes: "Gujarat marine terminal for Mangala / Barmer.",
    }),
    Hub({
      id: "dalian",
      name: "Dalian",
      country: "China",
      region: "Asia Pacific",
      lat: 38.93,
      lon: 121.65,
      role: "loading",
      related_ids: ["daqing"],
      notes: "Northeast China port; Daqing corridor export.",
    }),
    Hub({
      id: "qingdao",
      name: "Qingdao",
      country: "China",
      region: "Asia Pacific",
      lat: 36.08,
      lon: 120.32,
      role: "loading",
      related_ids: ["shengli"],
      notes: "Shandong port for Shengli and imports.",
    }),
    Hub({
      id: "arun-lhok",
      name: "Arun / Lhokseumawe",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 5.23,
      lon: 97.14,
      role: "loading",
      related_ids: ["arun"],
      notes: "North Sumatra condensate loading.",
    }),
    Hub({
      id: "exmouth-load",
      name: "Exmouth",
      country: "Australia",
      region: "Asia Pacific",
      lat: -21.9,
      lon: 114.15,
      role: "loading",
      related_ids: ["bree", "vincent", "enfield", "pyrenees"],
      notes: "Carnarvon / Exmouth offtake for Vincent, Enfield, Pyrenees, Bree.",
    }),
    Hub({
      id: "agbami-fpso",
      name: "Agbami FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 3.5,
      lon: 5.5,
      role: "loading",
      related_ids: ["agbami"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "akpo-fpso",
      name: "Akpo FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 3.2,
      lon: 6.5,
      role: "loading",
      related_ids: ["akpo"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "bonga-fpso",
      name: "Bonga FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 4.55,
      lon: 4.6,
      role: "loading",
      related_ids: ["bonga"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "erha-fpso",
      name: "Erha FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 4.3,
      lon: 4.9,
      role: "loading",
      related_ids: ["erha"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "usan-fpso",
      name: "Usan FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 3.9,
      lon: 7.3,
      role: "loading",
      related_ids: ["usan"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "egina-fpso",
      name: "Egina FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 3.8,
      lon: 6.5,
      role: "loading",
      related_ids: ["egina"],
      notes: "Deepwater Niger Delta FPSO loading.",
    }),
    Hub({
      id: "amenam-load",
      name: "Amenam / Odudu",
      country: "Nigeria",
      region: "Africa",
      lat: 4.2,
      lon: 7.6,
      role: "loading",
      related_ids: ["amenam"],
      notes: "Amenam-Kpono / Odudu loading system.",
    }),
    Hub({
      id: "ea-fpso",
      name: "EA FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 4.1,
      lon: 7.9,
      role: "loading",
      related_ids: ["ea-blend"],
      notes: "EA field FPSO loading.",
    }),
    Hub({
      id: "odudu-load",
      name: "Odudu",
      country: "Nigeria",
      region: "Africa",
      lat: 4.1,
      lon: 8.0,
      role: "loading",
      related_ids: ["odudu"],
      notes: "Odudu marine loading.",
    }),
    Hub({
      id: "antan-load",
      name: "Antan",
      country: "Nigeria",
      region: "Africa",
      lat: 4.2,
      lon: 8.2,
      role: "loading",
      related_ids: ["antan"],
      notes: "Antan terminal loading.",
    }),
    Hub({
      id: "okwori-fpso",
      name: "Okwori FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 3.9,
      lon: 6.8,
      role: "loading",
      related_ids: ["okwori"],
      notes: "Okwori FPSO loading.",
    }),
    Hub({
      id: "ebok-fpso",
      name: "Ebok FPSO",
      country: "Nigeria",
      region: "Africa",
      lat: 4.3,
      lon: 8.0,
      role: "loading",
      related_ids: ["ebok"],
      notes: "Ebok FPSO loading.",
    }),
    Hub({
      id: "zafiro-fpso",
      name: "Zafiro",
      country: "Equatorial Guinea",
      region: "Africa",
      lat: 3.8,
      lon: 8.0,
      role: "loading",
      related_ids: ["zafiro"],
      notes: "Zafiro complex FPSO / Punta Europa offtake.",
    }),
    Hub({
      id: "ceiba-fpso",
      name: "Ceiba / Serpentina",
      country: "Equatorial Guinea",
      region: "Africa",
      lat: 1.4,
      lon: 9.3,
      role: "loading",
      related_ids: ["ceiba"],
      notes: "Rio Muni FPSO loading.",
    }),
    Hub({
      id: "jubilee-fpso",
      name: "Jubilee FPSO",
      country: "Ghana",
      region: "Africa",
      lat: 4.5,
      lon: -2.9,
      role: "loading",
      related_ids: ["jubilee"],
      notes: "Tano Basin FPSO loading.",
    }),
    Hub({
      id: "baobab-fpso",
      name: "Baobab FPSO",
      country: "Côte d'Ivoire",
      region: "Africa",
      lat: 4.7,
      lon: -4.5,
      role: "loading",
      related_ids: ["baobab"],
      notes: "CI-40 FPSO loading.",
    }),
    Hub({
      id: "espoir-fpso",
      name: "Espoir FPSO",
      country: "Côte d'Ivoire",
      region: "Africa",
      lat: 5.0,
      lon: -4.3,
      role: "loading",
      related_ids: ["espoir"],
      notes: "CI-26 FPSO loading.",
    }),
    Hub({
      id: "sangomar-fpso",
      name: "Sangomar FPSO",
      country: "Senegal",
      region: "Africa",
      lat: 13.7,
      lon: -17.4,
      role: "loading",
      related_ids: ["sangomar"],
      notes: "Rufisque / Sangomar FPSO loading.",
    }),
    Hub({
      id: "nkossa-fpu",
      name: "N'Kossa",
      country: "Congo",
      region: "Africa",
      lat: -5.3,
      lon: 11.7,
      role: "loading",
      related_ids: ["n-kossa"],
      notes: "N'Kossa FPU loading.",
    }),
    Hub({
      id: "kitina-load",
      name: "Kitina",
      country: "Congo",
      region: "Africa",
      lat: -5.0,
      lon: 11.9,
      role: "loading",
      related_ids: ["kitina"],
      notes: "Kitina offshore loading.",
    }),
    Hub({
      id: "coral-sul",
      name: "Coral Sul",
      country: "Mozambique",
      region: "Africa",
      lat: -10.9,
      lon: 40.7,
      role: "loading",
      related_ids: ["coral-condensate"],
      notes: "Coral South FLNG condensate offtake.",
    }),
    Hub({
      id: "statfjord-load",
      name: "Statfjord",
      country: "Norway",
      region: "Europe",
      lat: 61.25,
      lon: 1.85,
      role: "loading",
      related_ids: ["statfjord"],
      notes: "Statfjord offshore tanker loading.",
    }),
    Hub({
      id: "gullfaks-load",
      name: "Gullfaks",
      country: "Norway",
      region: "Europe",
      lat: 61.2,
      lon: 2.2,
      role: "loading",
      related_ids: ["gullfaks"],
      notes: "Gullfaks offshore tanker loading.",
    }),
    Hub({
      id: "asgard-load",
      name: "Åsgard",
      country: "Norway",
      region: "Europe",
      lat: 65.0,
      lon: 6.5,
      role: "loading",
      related_ids: ["asgard"],
      notes: "Åsgard C FPSO loading.",
    }),
    Hub({
      id: "draugen-load",
      name: "Draugen",
      country: "Norway",
      region: "Europe",
      lat: 64.35,
      lon: 7.8,
      role: "loading",
      related_ids: ["draugen"],
      notes: "Draugen platform offshore loading.",
    }),
    Hub({
      id: "heidrun-load",
      name: "Heidrun",
      country: "Norway",
      region: "Europe",
      lat: 65.3,
      lon: 7.3,
      role: "loading",
      related_ids: ["heidrun"],
      notes: "Heidrun platform offshore loading.",
    }),
    Hub({
      id: "norne-fpso",
      name: "Norne FPSO",
      country: "Norway",
      region: "Europe",
      lat: 66.0,
      lon: 8.1,
      role: "loading",
      related_ids: ["norne"],
      notes: "Norne FPSO loading.",
    }),
    Hub({
      id: "alvheim-fpso",
      name: "Alvheim FPSO",
      country: "Norway",
      region: "Europe",
      lat: 59.5,
      lon: 2.0,
      role: "loading",
      related_ids: ["alvheim"],
      notes: "Alvheim FPSO loading.",
    }),
    Hub({
      id: "goliat-fpso",
      name: "Goliat FPSO",
      country: "Norway",
      region: "Europe",
      lat: 71.3,
      lon: 22.3,
      role: "loading",
      related_ids: ["goliat"],
      notes: "Barents Sea FPSO loading.",
    }),
    Hub({
      id: "castberg-fpso",
      name: "Johan Castberg FPSO",
      country: "Norway",
      region: "Europe",
      lat: 72.3,
      lon: 20.2,
      role: "loading",
      related_ids: ["johan-castberg"],
      notes: "Barents Sea FPSO loading.",
    }),
    Hub({
      id: "skarv-fpso",
      name: "Skarv FPSO",
      country: "Norway",
      region: "Europe",
      lat: 65.7,
      lon: 7.7,
      role: "loading",
      related_ids: ["skarv"],
      notes: "Norwegian Sea FPSO loading.",
    }),
    Hub({
      id: "njord-load",
      name: "Njord",
      country: "Norway",
      region: "Europe",
      lat: 64.3,
      lon: 7.2,
      role: "loading",
      related_ids: ["njord"],
      notes: "Njord A offshore loading.",
    }),
    Hub({
      id: "mariner-fpso",
      name: "Mariner FPSO",
      country: "United Kingdom",
      region: "Europe",
      lat: 59.6,
      lon: 1.1,
      role: "loading",
      related_ids: ["mariner"],
      notes: "UK North Sea heavy FPSO loading.",
    }),
    Hub({
      id: "gryphon-fpso",
      name: "Gryphon FPSO",
      country: "United Kingdom",
      region: "Europe",
      lat: 59.35,
      lon: 1.55,
      role: "loading",
      related_ids: ["gryphon"],
      notes: "UK North Sea FPSO loading.",
    }),
    Hub({
      id: "cinta-load",
      name: "Cinta",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: -5.5,
      lon: 106.5,
      role: "loading",
      related_ids: ["cinta"],
      notes: "Java Sea Cinta loading.",
    }),
    Hub({
      id: "widuri-load",
      name: "Widuri",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: -5.3,
      lon: 106.2,
      role: "loading",
      related_ids: ["widuri"],
      notes: "Java Sea Widuri loading.",
    }),
    Hub({
      id: "belanak-fpso",
      name: "Belanak FPSO",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 4.2,
      lon: 106.5,
      role: "loading",
      related_ids: ["belanak"],
      notes: "Natuna Sea FPSO loading.",
    }),
    Hub({
      id: "kikeh-fpso",
      name: "Kikeh FPSO",
      country: "Malaysia",
      region: "Asia Pacific",
      lat: 6.0,
      lon: 114.8,
      role: "loading",
      related_ids: ["kikeh"],
      notes: "Sabah deepwater FPSO loading.",
    }),
    Hub({
      id: "cossack-load",
      name: "Cossack Pioneer",
      country: "Australia",
      region: "Asia Pacific",
      lat: -19.5,
      lon: 116.0,
      role: "loading",
      related_ids: ["cossack"],
      notes: "North West Shelf FPSO offtake.",
    }),
    Hub({
      id: "banyu-urip-load",
      name: "Banyu Urip / Tuban",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: -7.2,
      lon: 111.6,
      role: "loading",
      related_ids: ["banyu-urip"],
      notes: "Cepu FSO / Tuban offtake.",
    }),
    Hub({
      id: "attaka-load",
      name: "Attaka",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 0.0,
      lon: 117.5,
      role: "loading",
      related_ids: ["attaka"],
      notes: "East Kalimantan Attaka loading.",
    }),
    Hub({
      id: "handil-load",
      name: "Handil",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: -0.5,
      lon: 117.3,
      role: "loading",
      related_ids: ["handil-mix"],
      notes: "Mahakam Handil loading.",
    }),
    Hub({
      id: "bekapai-load",
      name: "Bekapai",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 0.5,
      lon: 117.6,
      role: "loading",
      related_ids: ["bekapai"],
      notes: "Mahakam Bekapai loading.",
    }),
    Hub({
      id: "badak-load",
      name: "Badak",
      country: "Indonesia",
      region: "Asia Pacific",
      lat: 0.15,
      lon: 117.45,
      role: "loading",
      related_ids: ["badak"],
      notes: "East Kalimantan Badak loading.",
    }),
  ];

  global.HUBS_DATA = { hubs: hubs };
})(typeof window !== "undefined" ? window : globalThis);
